### ISSUE TITLE
Setup Search by City name function

### ISSUE THREAD

**Issue by shikdernyc** [Web-Dev-Speedrunners/melber-kt#3]
## Overview
- Location `src/search_api`
- Returns `Array<APIStateCityList>`
- Should call api endpoint to find all zipcodes for a city
- Should call `SearchForZipcode()` function to retrieve all cities for a given zipcode
- Should group all cities by state and convert it to `APIStateCityList` object

**Comment by rvente** [comment]
Closed in favor of pair programmed #8
